version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      # enter your docker host IP here
      ServerIP: "${LOCAL_IP}"
      # IPv6 Address if your network supports it
      #ServerIPv6: 
      # WEBPASSWORD: "piholepass"
    volumes:
       - "${DOCKER_CONFIGS}/pihole/:/etc/pihole/"
       - "${DOCKER_CONFIGS}/dnsmasq.d/:/etc/dnsmasq.d/"
    restart: always
